name: CI/CD Test Exemple Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Build-exemple:
    name: Build | Afficher le nom de l'utilisateur
    runs-on: ubuntu-latest
    steps:
      - name: Echo user login
        run: echo "Hello, ${{ github.actor }}"

  test:
    name: Build | Test 
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Test effectué depuis la branche ${{ github.ref_name }}"
